name: Build mod

on:
  push:
    branches: ["1.20.1-forge"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: merequester
          path: build/libs/*.jar
          if-no-files-found: error
